name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          echo "Deploying files to EC2 instance..."
          # The first command copies files to a temporary location in the ec2-user's home directory.
          scp -o StrictHostKeyChecking=no -r ./* ec2-user@44.199.204.177:/home/ec2-user/temp_deploy/

          # The second command connects via SSH and moves the files from the temporary location to the web directory using sudo.
          ssh -o StrictHostKeyChecking=no ec2-user@44.199.204.177 'sudo rm -rf /var/www/html/* && sudo mv /home/ec2-user/temp_deploy/* /var/www/html/'

          # New command: Create an .htaccess file to tell Apache to serve your file
          ssh -o StrictHostKeyChecking=no ec2-user@44.199.204.177 'echo "DirectoryIndex ci_cd_pipeline.html" | sudo tee /var/www/html/.htaccess'
